apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent
  namespace: prod
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: agent
  namespaceSelector:
    matchNames:
    - prod
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
