services:
  yolo:
    build:
      context: ./services/yolo
    image: hadikhier/yolo-service:${YOLO_IMAGE_TAG:-0.0.1}
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    volumes:
      - yolo-db:/app
      - ~/.aws:/root/.aws:ro
    networks:
      - polyai-net

  agent:
    build:
      context: ./services/agent
    image: hadikhier/agent-service:${AGENT_IMAGE_TAG:-0.0.2}
    ports:
      - "8000:8000"
    environment:
      YOLO_SERVICE_URL: http://yolo:8080
      MCP_SERVICE_URL: http://img-proc-mcp:9000/mcp
      MODEL: bedrock:amazon.nova-micro-v1:0
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    networks:
      - polyai-net
    depends_on:
      - yolo
      - img-proc-mcp
    volumes:
      - ~/.aws:/root/.aws:ro

  img-proc-mcp:
    build:
      context: ./services/img-proc-mcp
    image: hadikhier/img-proc-mcp:${MCP_IMAGE_TAG:-0.0.1}
    ports:
      - "9000:9000"
    networks:
      - polyai-net
    volumes:
      - ~/.aws:/root/.aws:ro

  frontend:
    build:
      context: ./services/frontend
    image: hadikhier/frontend-service:${FRONTEND_IMAGE_TAG:-0.0.1}
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_AGENT_URL: http://localhost:8000
    networks:
      - polyai-net
    depends_on:
      - agent

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring-net
      - polyai-net
    depends_on:
      - yolo

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3001"
    environment:
      GF_SERVER_HTTP_PORT: 3001
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-net
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    networks:
      - monitoring-net

volumes:
  grafana-storage:
  prometheus-data:
  yolo-db:

networks:
  polyai-net:
    driver: bridge
  monitoring-net:
    driver: bridge
