apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agent
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
  - host: agent-dev.hadi-polyai.fursa.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: agent
            port:
              number: 8000
