apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-prod
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi