name: Deploy PolyAI

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev instance
        uses: appleboy/ssh-action@v1
        with:
          host: dev.hadi.fursa.click
          username: ubuntu
          key: ${{ secrets.DEV_INSTANCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/Poly-fursa-AI
            git fetch origin
            git checkout dev
            git pull origin dev

            source .venv/bin/activate
            cat > services/yolo/.env <<EOF
            AWS_REGION=us-east-1
            AWS_S3_BUCKET=hadi-polyai-images-hk2026
            EOF
            pip install -r services/yolo/torch-requirements.txt
            pip install -r services/yolo/requirements.txt
            pip install -r services/agent/requirements.txt

            cd /home/ubuntu/Poly-fursa-AI/services/frontend
            npm install
            
            cd /home/ubuntu/Poly-fursa-AI
            sudo cp infrastructure/dev/yolo.service /etc/systemd/system/yolo.service
            sudo cp infrastructure/dev/poly-agent.service /etc/systemd/system/poly-agent.service
            sudo cp infrastructure/dev/poly-frontend.service /etc/systemd/system/poly-frontend.service

            sudo systemctl daemon-reload

            sudo systemctl restart yolo.service
            sudo systemctl restart poly-agent.service
            sudo systemctl restart poly-frontend.service

            sudo systemctl status yolo.service --no-pager
            sudo systemctl status poly-agent.service --no-pager
            sudo systemctl status poly-frontend.service --no-pager

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Prod instance
        uses: appleboy/ssh-action@v1
        with:
          host: prod.hadi.fursa.click
          username: ubuntu
          key: ${{ secrets.PROD_INSTANCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/Poly-fursa-AI
            git fetch origin
            git checkout main
            git pull origin main

            source .venv/bin/activate
            cat > services/yolo/.env <<EOF
            AWS_REGION=us-east-1
            AWS_S3_BUCKET=hadi-polyai-images-hk2026
            EOF

            pip install -r services/yolo/torch-requirements.txt
            pip install -r services/yolo/requirements.txt
            pip install -r services/agent/requirements.txt

            cd /home/ubuntu/Poly-fursa-AI/services/frontend
            npm install
            cd /home/ubuntu/Poly-fursa-AI
            sudo cp infrastructure/prod/yolo.service /etc/systemd/system/yolo.service
            sudo cp infrastructure/prod/poly-agent.service /etc/systemd/system/poly-agent.service
            sudo cp infrastructure/prod/poly-frontend.service /etc/systemd/system/poly-frontend.service
            sudo systemctl daemon-reload
            
            sudo systemctl restart yolo.service
            sudo systemctl restart poly-agent.service
            sudo systemctl restart poly-frontend.service

            sudo systemctl status yolo.service --no-pager
            sudo systemctl status poly-agent.service --no-pager
            sudo systemctl status poly-frontend.service --no-pager